// <auto-generated />
namespace SoLoud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTitleToContest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTitleToContest));
        
        string IMigrationMetadata.Id
        {
            get { return "201610301410303_addTitleToContest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
